dbt_project:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: mq89355.canada-central.azure
      user: NCSTUDIOS316
      password: 
      role: 
      database: MARKETDATA
      warehouse: COMPUTE_WH
      schema: MARKET
      threads: 4

