WITH daily_stock_prices AS (
    SELECT
        Source as Ticker,
        Date as Trade_Date,
        Open as Open_Price,
        High as High_Price,
        Low as Low_Price,
        Close as Close_Price,
        Volume as Trade_Volume,
        Year as Trade_Year,
        Month as Trade_Month,
        Day as Trade_Day,
        DayOfWeek as Trade_Day_of_Week,
        DayOfWeek as Trade_Day_of_Year,
        WeekOfYear as Trade_Week_of_Year,
        Quarter as Trade_Quarter,
        IsMonthStart as Is_Start_of_Month,
        IsMonthEnd as Is_End_of_Month,
        IsQuarterStart as Is_Start_of_Quarter,
        IsQuarterEnd as Is_End_of_Quarter,
        PriceChange as Price_Change_Pct,
        HighLowRange as High_Low_Range_Pct,
        CloseOpenRange as Close_Open_Range_Pct,
        PercentChange as Percent_Change_Pct,
        SMA_5 as SMA_5_Day,
        EMA_5 as EMA_5_Day,
        SMA_10 as SMA_10_Day,
        EMA_10 as EMA_10_Day,
        SMA_20 as SMA_20_Day,
        EMA_20 as EMA_20_Day,
        SMA_50 as SMA_50_Day,
        EMA_50 as EMA_50_Day,
        SMA_100 as SMA_100_Day,
        EMA_100 as EMA_100_Day,
        SMA_200 as SMA_200_Day,
        EMA_200 as EMA_200_Day,
        Volatility_20 as Volatility_20_Day,
        RSI as RSI_Value,
        EMA_12 as EMA_12_Day,
        EMA_26 as EMA_26_Day,      
        MACD as MACD_Value,
        SIGNAL_LINE as Signal_Line,
        PLUSDI as Plus_DI,
        MINUSDI as Minus_DI,
        ADX as ADX_Value,
        SAR as SAR_Value,
        Volume_20 as Volume_20_Day,
        Volume_50 as Volume_50_Day,
        BB_Middle as BB_Middle,
        BB_Upper as BB_Upper,
        BB_Lower as BB_Lower,
        Stochastic as Stochastic_Value,
        CCI as CCI_Value
    FROM {{ source('src_daily_stock_prices', 'DAILY_STOCKS') }}
)

SELECT
    *
FROM daily_stock_prices
